"""criar tabelas livros usuarios emprestimos

Revision ID: 144c6261b0a6
Revises: 
Create Date: 2026-07-31 18:54:17.792738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144c6261b0a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('quantidade_total', sa.Integer(), nullable=False),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('data_devolucao_prevista', sa.Date(), nullable=False),
    sa.Column('data_devolucao_real', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprestimos')
    op.drop_table('usuarios')
    op.drop_table('livros')
    # ### end Alembic commands ###
