"""Adiciona a regra Unique em email de usuarios

Revision ID: cbd94ec9c473
Revises: 144c6261b0a6
Create Date: 2026-07-31 20:30:26.640606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd94ec9c473'
down_revision: Union[str, Sequence[str], None] = '144c6261b0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_usuarios_email', ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuarios_email', type_='unique')

    # ### end Alembic commands ###
