"""adiciona genero em livros

Revision ID: ded465f6bc53
Revises: a88d8257b686
Create Date: 2026-08-11 13:59:06.656736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded465f6bc53'
down_revision: Union[str, Sequence[str], None] = 'a88d8257b686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('genero', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livros', 'genero')
    # ### end Alembic commands ###
